# Generated by Django 2.2.5 on 2021-01-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_userprofile_phonenumber'),
        ('appProduct', '0029_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userProfile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.UserProfile'),
        ),
    ]
